DELETE FROM `ps_category` WHERE id_category NOT IN (2, 1);
DELETE FROM `ps_category_lang` WHERE id_category NOT IN (2, 1);
DELETE FROM `ps_category_shop` WHERE id_category NOT IN (2, 1);

TRUNCATE TABLE `ps_product`;
TRUNCATE TABLE `ps_product_shop`;
TRUNCATE TABLE `ps_feature_product`;
TRUNCATE TABLE `ps_product_lang`;
TRUNCATE TABLE `ps_category_product`;
TRUNCATE TABLE `ps_product_tag`;
TRUNCATE TABLE `ps_tag`;
TRUNCATE TABLE `ps_image`;
TRUNCATE TABLE `ps_image_lang`;
TRUNCATE TABLE `ps_image_shop`;
TRUNCATE TABLE `ps_specific_price`;
TRUNCATE TABLE `ps_specific_price_priority`;
TRUNCATE TABLE `ps_product_carrier`;
TRUNCATE TABLE `ps_cart_product`;
TRUNCATE TABLE `ps_compare_product`;
TRUNCATE TABLE `ps_product_attachment`;
TRUNCATE TABLE `ps_product_country_tax`;
TRUNCATE TABLE `ps_product_download`;
TRUNCATE TABLE `ps_product_group_reduction_cache`;
TRUNCATE TABLE `ps_product_sale`;
TRUNCATE TABLE `ps_product_supplier`;
TRUNCATE TABLE `ps_scene_products`;
TRUNCATE TABLE `ps_warehouse_product_location`;
TRUNCATE TABLE `ps_stock`;
TRUNCATE TABLE `ps_stock_available`;
TRUNCATE TABLE `ps_stock_mvt`;
TRUNCATE TABLE `ps_customization`;
TRUNCATE TABLE `ps_customization_field`;
TRUNCATE TABLE `ps_supply_order_detail`;
TRUNCATE TABLE `ps_attribute_impact`;
TRUNCATE TABLE `ps_product_attribute`;
TRUNCATE TABLE `ps_product_attribute_shop`;
TRUNCATE TABLE `ps_product_attribute_combination`;
TRUNCATE TABLE `ps_product_attribute_image`;
TRUNCATE TABLE `ps_attribute`;
TRUNCATE TABLE `ps_attribute_impact`;
TRUNCATE TABLE `ps_attribute_lang`;
TRUNCATE TABLE `ps_attribute_group`;
TRUNCATE TABLE `ps_attribute_group_lang`;
TRUNCATE TABLE `ps_attribute_group_shop`;
TRUNCATE TABLE `ps_attribute_shop`;
TRUNCATE TABLE `ps_product_attribute`;
TRUNCATE TABLE `ps_product_attribute_shop`;
TRUNCATE TABLE `ps_product_attribute_combination`;
TRUNCATE TABLE `ps_product_attribute_image`;
TRUNCATE TABLE `ps_stock_available`;
TRUNCATE TABLE `ps_manufacturer`;
TRUNCATE TABLE `ps_manufacturer_lang`;
TRUNCATE TABLE `ps_manufacturer_shop`;
TRUNCATE TABLE `ps_supplier`;
TRUNCATE TABLE `ps_supplier_lang`;
TRUNCATE TABLE `ps_supplier_shop`;
TRUNCATE TABLE `ps_customization`;
TRUNCATE TABLE `ps_customization_field`;
TRUNCATE TABLE `ps_customization_field_lang`;
TRUNCATE TABLE `ps_customized_data`;
TRUNCATE TABLE `ps_feature`;
TRUNCATE TABLE `ps_feature_lang`;
TRUNCATE TABLE `ps_feature_product`;
TRUNCATE TABLE `ps_feature_shop`;
TRUNCATE TABLE `ps_feature_value`;
TRUNCATE TABLE `ps_feature_value_lang`;
TRUNCATE TABLE `ps_pack`;
TRUNCATE TABLE `ps_scene`;
TRUNCATE TABLE `ps_scene_category`;
TRUNCATE TABLE `ps_scene_lang`;
TRUNCATE TABLE `ps_scene_products`;
TRUNCATE TABLE `ps_scene_shop`;
TRUNCATE TABLE `ps_search_index`;
TRUNCATE TABLE `ps_search_word`;
TRUNCATE TABLE `ps_specific_price`;
TRUNCATE TABLE `ps_specific_price_priority`;
TRUNCATE TABLE `ps_specific_price_rule`;
TRUNCATE TABLE `ps_specific_price_rule_condition`;
TRUNCATE TABLE `ps_specific_price_rule_condition_group`;
TRUNCATE TABLE `ps_stock`;
TRUNCATE TABLE `ps_stock_available`;
TRUNCATE TABLE `ps_stock_mvt`;
TRUNCATE TABLE `ps_warehouse`;

DELETE FROM `ps_address` WHERE id_manufacturer > 0 OR id_supplier > 0 OR id_warehouse > 0;

TRUNCATE TABLE `ps_customer`;
TRUNCATE TABLE `ps_cart`;
TRUNCATE TABLE `ps_cart_product`;
TRUNCATE TABLE `ps_connections`;
TRUNCATE TABLE `ps_connections_page`;
TRUNCATE TABLE `ps_connections_source`;
TRUNCATE TABLE `ps_customer_group`;
TRUNCATE TABLE `ps_customer_message`;
TRUNCATE TABLE `ps_customer_message_sync_imap`;
TRUNCATE TABLE `ps_customer_thread`;
TRUNCATE TABLE `ps_guest`;
TRUNCATE TABLE `ps_message`;
TRUNCATE TABLE `ps_message_readed`;
TRUNCATE TABLE `ps_orders`;
TRUNCATE TABLE `ps_order_carrier`;
TRUNCATE TABLE `ps_order_cart_rule`;
TRUNCATE TABLE `ps_order_detail`;
TRUNCATE TABLE `ps_order_detail_tax`;
TRUNCATE TABLE `ps_order_history`;
TRUNCATE TABLE `ps_order_invoice`;
TRUNCATE TABLE `ps_order_invoice_payment`;
TRUNCATE TABLE `ps_order_invoice_tax`;
TRUNCATE TABLE `ps_order_message`;
TRUNCATE TABLE `ps_order_message_lang`;
TRUNCATE TABLE `ps_order_payment`;
TRUNCATE TABLE `ps_order_return`;
TRUNCATE TABLE `ps_order_return_detail`;
TRUNCATE TABLE `ps_order_slip`;
TRUNCATE TABLE `ps_order_slip_detail`;
TRUNCATE TABLE `ps_page`;
TRUNCATE TABLE `ps_page_type`;
TRUNCATE TABLE `ps_page_viewed`;
TRUNCATE TABLE `ps_product_sale`;
TRUNCATE TABLE `ps_referrer_cache`;
TRUNCATE TABLE `ps_sekeyword`;
TRUNCATE TABLE `ps_pagenotfound`;

DELETE FROM `ps_address` WHERE id_customer > 0;
UPDATE `ps_employee` SET `id_last_order` = 0,`id_last_customer_message` = 0,`id_last_customer` = 0;

UPDATE ps_configuration
SET value = 0
WHERE name = 'PS_DASHBOARD_SIMULATION';